name: Assign Issue2

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  assign:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign the user or unassign stale assignments
        uses: jaydee029/issue_assignment_bot@v1.1.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Commands to run
          commands: /assign
