name: Rasqberry Pi Image Release

on:
  # push:
  #   branches:
  #     - arm64
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: New version number in X.Y.Z
        required: true

## Use `bash --noprofile --norc -exo pipefail` by default for all `run` steps in this workflow:
## https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun
#defaults:
#  run:
#    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  rasqberry-push-version-number:
    name: "Rasqberry: Push version number"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.current-version.outputs.version }}
    steps:
      - name: "Rasqberry: Clone Repository"
        uses: actions/checkout@v4
        with:
          repository: "dasanind/RasQberry-pi-gen"
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
#          ref: "30-sw-platform"

      - name: "Rasqberry: Get current version"
        id: current-version
        shell: bash
        run: |
          version=$(cat ./src/version)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - run: |
          echo "${{ steps.current-version.outputs.version }}"

      - name: "Rasqberry: Add version file"
        if: steps.current-version.outputs.version != github.event.inputs.version
        shell: bash
        run: |
          echo ${{ github.event.inputs.version }} > ./src/version

      - name: "Rasqberry: git add & commit & tag & push"
        uses: EndBug/add-and-commit@v9
        with:
          add: "./src/version"
          default_author: github_actions
          message: "Bump version to v${{ github.event.inputs.version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ github.event.inputs.version }} --force"
          tag_push: "--force"
          push: true

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'
      - name: Check install!
        run: cosign version

  release:
    name: Create Release
    needs: rasqberry-push-version-number
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.create-release.outputs.id }}
      date: ${{ steps.base-name.outputs.date }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # ref: "v2.1.x"
          fetch-depth: 0

      - name: Get latest tag
        id: latest_tag
        shell: bash
        run: |
          echo "TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - run: |
          echo "${{ steps.latest_tag.outputs.TAG_NAME }}"      

      - name: Print branch details
        id: branch-details
        shell: bash
        run: |
          echo "branch_name=$(git branch --show-current)" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.branch-details.outputs.branch_name }}"

#      - name: Print branch status
#        id: branch-status
#        shell: bash
#        run: |
#          status=$(echo $(git status) | tr '\n' ' ')
#          echo "branch_status=$status" >> $GITHUB_OUTPUT
#      - run: |
#          echo "${{ steps.branch-details.outputs.branch_status }}"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        id: changelog
        with:
          config: ./cliff-release.toml
          args: ${{ steps.latest_tag.outputs.TAG_NAME }}..HEAD

      - name: Create empty release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "rasqberry-v${{ github.event.inputs.version }}"
          tag_name: v${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.content }}
          draft: true

      - name: Create Date
        id: base-name
        if: always()
        shell: bash
        run: |
          NOW="$(date +"%Y-%m-%d")"
          echo "date=${NOW}" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.base-name.outputs.date }}"
  matrix:
    name: Create Matrix
    needs: release
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
#        with:
#          ref: v2.1.x

      - name: Create Matrix
        id: set-matrix
        shell: bash
        run: |
          PY_INT=$(command -v python3)
          CONFIG="${{ github.workspace }}/.github/workflow_config.yml"
          GROUP="release"
          $PY_INT ${{ github.workspace }}/.github/scripts/setup_matrix.py -c $CONFIG -g $GROUP --git

  build:
    needs: [release, matrix]
    runs-on: ubuntu-latest
#    outputs:
#      base_name: ${{ steps.move-image.outputs.base_name }}
#    strategy:
#      fail-fast: false
#      matrix:
#        config: ${{ fromJson(needs.matrix.outputs.matrix) }}

    steps:
      - name: setraspiconfig
        uses: usimd/pi-gen-action@v1
        id: pi-gen-build
        with:
#          config: ${{ matrix.config }}
          apt-proxy: ''
          compression: xz
          compression-level: 8
          disable-first-boot-user-rename: 0
          pi-gen-repository: dasanind/RasQberry-pi-gen
          pi-gen-version: arm64
          docker-opts: ''
          enable-noobs: false
          enable-ssh: 0
          export-last-stage-only: true
          extra-host-dependencies: ''
          extra-host-modules: ''
          github-token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          hostname: raspberrypi
          image-name: 'rasqberry-two'
          increase-runner-disk-size: true
          keyboard-keymap: gb
          keyboard-layout: English (UK)
          locale: en_GB.UTF-8
          password: 'Qiskit1!'
          pi-gen-release: Raspberry Pi Qiskit Release
          pubkey-only-ssh: 0
          stage-list: stage0 stage1 stage2 stage3 stage4 stage5
          timezone: Europe/London
          verbose-output: true
     
     #  - name: Set dynamic asset path and name
     #    id: set_output
     #    run: |
     #      # Find the file dynamically in the 'deploy' directory
     #      FILE_PATH= ${{steps.pi-gen-build.outputs.image-path }}
     #      FILE_NAME=$(basename "$FILE_PATH")
     #      echo "asset_path=$FILE_PATH" >> $GITHUB_ENV
     #      echo "asset_name=$FILE_NAME" >> $GITHUB_ENV
     
     #  - name: Upload Release Asset to Target Repository
     #    uses: actions/upload-release-asset@v1
     #    with:
     #      upload_url: ${{ steps.create_release.outputs.upload_url }}
     #      asset_path: ${{ steps.pi-gen-build.outputs.image-path }}
     #      asset_name: ${{ env.asset_name }}
     #      asset_content_type: application/x-xz  
          
     #  # - name: Checkout target repository
     #  #   uses: checkout@v4
     #  #    # with:
     #  #    #   repository: "dasanind/RasQberry-pi-gen"  # Replace with target repository
     #  #    #   token: ${{ secrets.GITHUB_TOKEN }}
  
     #  #  # Install the cosign tool except on PR
     #  #  # https://github.com/sigstore/cosign-installer
     #  # - name: Install cosign
     #  #   uses: sigstore/cosign-installer@v3.5.0
     #  #   with:
     #  #      cosign-release: 'v2.2.4'
     #  # - name: Check install!
     #    run: cosign version

     # # - name: Create Release in Target Repository
     # #   id: create_release
     # #   uses: actions/create-release@v1
     # #   with:
     # #     tag_name: "v1.0"  # Update as needed
     # #     release_name: "Raspberry Pi Image"
     # #     draft: false
     # #     prerelease: false
     # #   env:
     # #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
     #   - name: Print branch details
     #   run: |
     #     echo "Branch details:"
     #     git branch --show-current  # Print the current branch name
     #     git status                 # Show the status of the working directory

     # - name: setraspiconfig
     #   uses: usimd/pi-gen-action@v1
     #   id: pi-gen-build
     #   with:
     #     apt-proxy: ''
     #     compression: xz
     #     compression-level: 8
     #     disable-first-boot-user-rename: 0
     #     pi-gen-repository: dasanind/RasQberry-pi-gen
     #     pi-gen-version: arm64
     #     docker-opts: ''
     #     enable-noobs: false
     #     enable-ssh: 0
     #     export-last-stage-only: true
     #     extra-host-dependencies: ''
     #     extra-host-modules: ''
     #     github-token: ${{ secrets.SECRET_GITHUB_TOKEN }}
     #     hostname: raspberrypi
     #     image-name: 'rasqberry-two'
     #     increase-runner-disk-size: true
     #     keyboard-keymap: gb
     #     keyboard-layout: English (UK)
     #     locale: en_GB.UTF-8
     #     password: 'Qiskit1!'
     #     pi-gen-release: Raspberry Pi Qiskit Release
     #     pubkey-only-ssh: 0
     #     stage-list: stage0 stage1 stage2 stage3 stage4 stage5
     #     timezone: Europe/London
     #     verbose-output: true
     # - name: Set dynamic asset path and name
     #   id: set_output
     #   run: |
     #     # Find the file dynamically in the 'deploy' directory
     #     FILE_PATH= ${{steps.pi-gen-build.outputs.image-path }}
     #     FILE_NAME=$(basename "$FILE_PATH")
     #     echo "asset_path=$FILE_PATH" >> $GITHUB_ENV
     #     echo "asset_name=$FILE_NAME" >> $GITHUB_ENV
     # - name: Upload Release Asset to Target Repository
     #   uses: actions/upload-release-asset@v1
     #   with:
     #     upload_url: ${{ steps.create_release.outputs.upload_url }}
     #     asset_path: ${{ steps.pi-gen-build.outputs.image-path }}
     #     asset_name: ${{ env.asset_name }}
     #     asset_content_type: application/x-xz
